'use strict';

const STATUS_CODE_SUCCESS = 200;
const STATUS_CODE_CREATE = 201;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_ERROR = 500;

module.exports = {
    STATUS_CODE_ERROR: STATUS_CODE_ERROR,
    STATUS_CODE_SUCCESS: STATUS_CODE_SUCCESS,
    STATUS_CODE_CREATE: STATUS_CODE_CREATE,
    STATUS_CODE_BAD_REQUEST: STATUS_CODE_BAD_REQUEST
};